name = "z3connectwebsitenew"
main = "index.html"
compatibility_date = "2024-12-19"

[env.production]
name = "z3connectwebsitenew"

[build]
command = ""
cwd = "."

[site]
bucket = "z3connectwebsite-main"
